Add copy button to glyph pages
kwiliarty/glyphworks pull request #92
Opened 2023-01-23 01:22 UTC by andyzito

2023-01-23 12:26 UTC, kwiliarty requested changes
I've requested some small changes here. Besides that, could you add something to the jest testing for this component? There's an example of a similar test in `main/components/IpaPairedInput/IpaPairedInput.test.js`. The tests are in an interesting space between unit tests and end-to-end tests. Let me know if you want to chat about it.

2023-01-23 12:26 UTC, kwiliarty commented on main/components/ClipboardCopy/ClipboardCopy.js
> +
I think we can should just remove `StyledIconPosition`.

2023-01-23 12:26 UTC, kwiliarty commented on main/components/ClipboardCopy/ClipboardCopy.js
> +  height: 2.2rem;
Let's change these `rem`s to `em`s. I think these values should depend on the current font size. I know that I put one of them in there, but I'm just re-thinking it.

2023-01-23 12:26 UTC, kwiliarty commented on main/components/ClipboardCopy/ClipboardCopy.js
> +  ${ StyledIconPosition }
This `StyledIconPosition` can go.

2023-01-23 12:26 UTC, kwiliarty commented on main/components/ClipboardCopy/ClipboardCopy.js
> +  ${ StyledIconPosition }
This `StyledIconPosition` can go.

2023-01-23 12:26 UTC, kwiliarty commented on main/components/ClipboardCopy/ClipboardCopy.js
> +  /** A background color name */
I think the comment should be "A text color name"

2023-01-23 12:28 UTC, kwiliarty commented
Oh, I just noticed that this is actually still a draft. Sorry if I jumped in too soon. Anyway, maybe the feedback is still helpful?

2023-01-24 11:50 UTC, andyzito commented
Not at all, thank you for catching those things. They should all be resolved in the latest commit.

2023-01-24 11:57 UTC, andyzito commented
@kwiliarty Is this what you had in mind for tests? Not 100% sure the `expectToBeCalled` lines are correct, but the tests pass.

2023-01-25 12:03 UTC, kwiliarty approved these changes
That looks great, and the test is right. It just ensures that the click calls the intended function with the intended argument. Thanks so much for this!

2023-01-25 12:04 UTC, kwiliarty commented
@andyzito : This is still marked as a draft. Was there something else you wanted to do on it, or do you think it's ready to go?

2023-01-25 14:45 UTC, andyzito commented
@kwiliarty Ready!

2023-01-26 11:52 UTC, closed without merging